/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPiloto;
import javax.swing.JTextField;

/**
 *
 * @author Miguel Ángel
 */
public class VistaPilotoAutomatico extends javax.swing.JFrame {
    
    ControladorPiloto controlador;
    /**
     * Creates new form VistaPilotoAutomatico
     */
    public VistaPilotoAutomatico() {
        initComponents();
        controlador = new ControladorPiloto(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldAltitud = new javax.swing.JTextField();
        jTextFieldRumbo = new javax.swing.JTextField();
        jButtonSumarAltitud = new javax.swing.JButton();
        jButtonRestarAltitud = new javax.swing.JButton();
        jButtonSumarRumbo = new javax.swing.JButton();
        jButtonRestarRumbo = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelAltitud = new javax.swing.JLabel();
        jLabelRumbo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldAltitud.setText("0");
        jTextFieldAltitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAltitudActionPerformed(evt);
            }
        });

        jTextFieldRumbo.setText("0");

        jButtonSumarAltitud.setText("+");
        jButtonSumarAltitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumarAltitudActionPerformed(evt);
            }
        });

        jButtonRestarAltitud.setText("-");
        jButtonRestarAltitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestarAltitudActionPerformed(evt);
            }
        });

        jButtonSumarRumbo.setText("+");
        jButtonSumarRumbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumarRumboActionPerformed(evt);
            }
        });

        jButtonRestarRumbo.setText("-");
        jButtonRestarRumbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestarRumboActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelAltitud.setText("Altitud");

        jLabelRumbo.setText("Rumbo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRumbo)
                    .addComponent(jLabelAltitud))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSumarAltitud)
                    .addComponent(jButtonSumarRumbo))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRumbo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAltitud, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRestarAltitud)
                            .addComponent(jButtonRestarRumbo)))
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAltitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSumarAltitud)
                    .addComponent(jLabelAltitud)
                    .addComponent(jButtonRestarAltitud))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRestarRumbo)
                    .addComponent(jTextFieldRumbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSumarRumbo)
                    .addComponent(jLabelRumbo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAltitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAltitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAltitudActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonSumarAltitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumarAltitudActionPerformed
        controlador.sumarAltitud();
    }//GEN-LAST:event_jButtonSumarAltitudActionPerformed

    private void jButtonRestarAltitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestarAltitudActionPerformed
        // TODO add your handling code here:
        controlador.restarAltitud();
    }//GEN-LAST:event_jButtonRestarAltitudActionPerformed

    private void jButtonSumarRumboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumarRumboActionPerformed
        // TODO add your handling code here:
        controlador.sumarRumbo();
    }//GEN-LAST:event_jButtonSumarRumboActionPerformed

    private void jButtonRestarRumboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestarRumboActionPerformed
        // TODO add your handling code here:
        controlador.restarRumbo();
    }//GEN-LAST:event_jButtonRestarRumboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPilotoAutomatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPilotoAutomatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPilotoAutomatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPilotoAutomatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPilotoAutomatico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRestarAltitud;
    private javax.swing.JButton jButtonRestarRumbo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSumarAltitud;
    private javax.swing.JButton jButtonSumarRumbo;
    private javax.swing.JLabel jLabelAltitud;
    private javax.swing.JLabel jLabelRumbo;
    private javax.swing.JTextField jTextFieldAltitud;
    private javax.swing.JTextField jTextFieldRumbo;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextFieldAltitud() {
        return jTextFieldAltitud;
    }

    public JTextField getjTextFieldRumbo() {
        return jTextFieldRumbo;
    }

}
